services:
  postgres:
    image: postgres:16
    container_name: ts-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts_backend
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ts_backend"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
